import { ROLES } from "./roles.js"

export const PERMISSIONS = {
  VIEW_DASHBOARD: "VIEW_DASHBOARD",
  VIEW_RECORDS: "VIEW_RECORDS",
  CREATE_RECORD: "CREATE_RECORD",
  UPDATE_RECORD: "UPDATE_RECORD",
  DELETE_RECORD: "DELETE_RECORD",
  MANAGE_USERS: "MANAGE_USERS"
}

export const ROLE_PERMISSIONS = {
  [ROLES.VIEWER]: [PERMISSIONS.VIEW_DASHBOARD],

  [ROLES.ANALYST]: [
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.VIEW_RECORDS,
  ],

  [ROLES.ADMIN]: Object.values(PERMISSIONS)
}